title:             With Jack
email:             superjack95@gmail.com
description:       With Jack, 승재랑.
author:            Start Bootstrap
baseurl:           "/"
url:               "http://withjack.github.io"

# Social Profiles
twitter_username:  null
github_username:   withJack
facebook_username: 이승재(Lee)

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

