title:             With Jack
email:             superjack95@gmail.com
description:       Success is not final, Failure is not fatal It is the courage to continue that counts.
author:            With Jack, 승재랑.
baseurl:           "/"
url:               "http://withjack.github.io"

# Social Profiles
twitter_username:  null
github_username:   withJack
facebook_username: null


# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

